import { redirect } from "next/navigation";
import { getSession } from "@/lib/session";
import { prisma } from "@/lib/db";
import Link from "next/link";
import PrintButton from "@/components/PrintButton";

export default async function PrintPage() {
  const session = await getSession();
  if (!session.userId) redirect("/login");

  const screenings = await prisma.screening.findMany({
    where: { archivedAt: null },
    orderBy: { screeningDatetime: "desc" },
    include: {
      patient: true,
      enteredBy: { select: { fullName: true, cadre: true } },
      reviewedBy: { select: { fullName: true } },
    },
  });

  const isManager = session.role === "MANAGER" || session.role === "ADMIN";

  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { font-size: 11px; }
          table { font-size: 10px; }
        }
        body { font-family: Arial, sans-serif; }
      `}</style>

      <div className="no-print d-flex flex-wrap align-items-center gap-2 p-3 bg-light border-bottom">
        <PrintButton />
        <Link href="/reports"
          style={{
            background: "#6c757d", color: "#fff", border: "none",
            padding: "8px 16px", borderRadius: 6, textDecoration: "none",
            fontSize: "0.9rem"
          }}>
          ← Back to Reports
        </Link>
        <span style={{ fontSize: "0.8rem", color: "#666" }}>
          On mobile: tap Print then choose Save as PDF
        </span>
      </div>

      <div className="container-fluid py-4 px-3 px-md-4">
        <div className="text-center mb-4">
          <h1 style={{ fontSize: "1.3rem", color: "#1a5276" }}>
            OGH SCD E-Tracker — Screening Report
          </h1>
          <div style={{ fontSize: "0.85rem", color: "#666" }}>
            Oda Government Hospital · Birim Central Municipal · Eastern Region · Ghana
          </div>
          <div style={{ fontSize: "0.8rem", color: "#666", marginTop: 4 }}>
            Generated by: <strong>{session.fullName}</strong> ({session.role}) ·{" "}
            {new Date().toLocaleString("en-GB")}
          </div>
          <div style={{ fontSize: "0.8rem", color: "#666" }}>
            Total Records: <strong>{screenings.length}</strong>
          </div>
        </div>

        <div className="row g-2 mb-4">
          {[
            { label: "Total Screenings", value: screenings.length },
            { label: "Catch-Up", value: screenings.filter(s => s.screeningType === "CATCH_UP").length },
            { label: "Newborn", value: screenings.filter(s => s.screeningType === "NEWBORN").length },
            { label: "Approved", value: screenings.filter(s => s.reviewStatus === "APPROVED").length },
            { label: "Pending Review", value: screenings.filter(s => s.reviewStatus === "PENDING").length },
            { label: "On Treatment", value: screenings.filter(s => s.treatmentStarted).length },
          ].map(k => (
            <div key={k.label} className="col-4 col-md-2">
              <div className="border rounded p-2 text-center">
                <div style={{ fontSize: "0.7rem", color: "#666" }}>{k.label}</div>
                <div style={{ fontSize: "1.2rem", fontWeight: "bold", color: "#1a5276" }}>
                  {k.value}
                </div>
              </div>
            </div>
          ))}
        </div>

        <div style={{ overflowX: "auto" }}>
          <table className="table table-bordered table-sm"
            style={{ fontSize: "0.75rem", minWidth: 700 }}>
            <thead style={{ background: "#1a5276", color: "#fff" }}>
              <tr>
                <th>#</th>
                <th>Patient ID</th>
                <th>Name</th>
                <th>Sex</th>
                <th>DOB</th>
                {isManager && <th>Phone</th>}
                <th>Locality</th>
                <th>Date</th>
                <th>Type</th>
                <th>Result</th>
                <th>Confirmatory</th>
                <th>Treatment</th>
                <th>Status</th>
                <th>Entered By</th>
                {isManager && <th>Reviewed By</th>}
              </tr>
            </thead>
            <tbody>
              {screenings.map((s, i) => (
                <tr key={s.id} style={{ background: i % 2 === 0 ? "#fff" : "#f8f9fa" }}>
                  <td>{i + 1}</td>
                  <td style={{ fontFamily: "monospace", fontSize: "0.7rem" }}>
                    {s.patient.patientCode}
                  </td>
                  <td>{s.patient.firstName} {s.patient.lastName}</td>
                  <td>{s.patient.sex}</td>
                  <td>{new Date(s.patient.dateOfBirth).toLocaleDateString("en-GB")}</td>
                  {isManager && <td>{s.patient.phoneNumber || "—"}</td>}
                  <td>{s.patient.locality || "—"}</td>
                  <td>{new Date(s.screeningDatetime).toLocaleDateString("en-GB")}</td>
                  <td>
                    <span style={{
                      background: s.screeningType === "NEWBORN" ? "#0dcaf0" : "#0d6efd",
                      color: s.screeningType === "NEWBORN" ? "#000" : "#fff",
                      padding: "1px 4px", borderRadius: 3, fontSize: "0.65rem"
                    }}>
                      {s.screeningType === "CATCH_UP" ? "Catch-Up" : "Newborn"}
                    </span>
                  </td>
                  <td style={{ fontSize: "0.7rem" }}>{s.screeningResult}</td>
                  <td>{s.confirmatoryAction}</td>
                  <td>
                    <span style={{
                      color: s.treatmentStarted ? "green" : "red", fontWeight: "bold"
                    }}>
                      {s.treatmentStarted ? "Yes" : "No"}
                    </span>
                  </td>
                  <td>
                    <span style={{
                      background: s.reviewStatus === "APPROVED" ? "#198754" :
                        s.reviewStatus === "PENDING" ? "#ffc107" :
                        s.reviewStatus === "FLAGGED" ? "#dc3545" : "#0dcaf0",
                      color: s.reviewStatus === "PENDING" ? "#000" : "#fff",
                      padding: "1px 4px", borderRadius: 3, fontSize: "0.65rem"
                    }}>
                      {s.reviewStatus}
                    </span>
                  </td>
                  <td>{s.enteredBy.fullName}</td>
                  {isManager && <td>{s.reviewedBy?.fullName || "—"}</td>}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-4 pt-3 border-top text-center"
          style={{ fontSize: "0.75rem", color: "#666" }}>
          <p className="mb-1">
            <strong>OGH SCD E-Tracker</strong> · Oda Government Hospital ·
            Birim Central Municipal · Eastern Region · Ghana
          </p>
          <p className="mb-0">
            This report is confidential and intended for authorised personnel only.
          </p>
        </div>
      </div>
    </>
  );
}
